db:
  host: 172.2.201.2
  user: stream
  password: stream
  port: 3306
  name: stream

redis:
  url: 172.2.150.2:6379

nats:
  url: nats://172.2.150.1:4222

drops:
  url:
    code: http://172.2.20.2/drops/oauth2/code/get
    redirect: http://172.2.20.2/auth/newbackend/code
    token: http://172.2.20.2/drops/oauth2/access_token
    user: http://172.2.20.2/drops/oauth2/rest/profile
  oauth:
    clientid: streamer


