-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 12:48:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stream
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stream
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stream` ;
USE `stream` ;

-- -----------------------------------------------------
-- Table `stream`.`taking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`taking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `received` BIGINT(20) NULL,
  `description` VARCHAR(255) NULL,
  `comment` MEDIUMTEXT NULL,
  `category` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`deposit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `date_of_deposit` BIGINT(20) NULL,
  `updated` BIGINT(20) NULL,
  `created` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taking_id` INT NOT NULL,
  `amount` INT NULL,
  `currency` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `norms` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `type_of_source` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_source_taking1_idx` (`taking_id` ASC) VISIBLE,
  CONSTRAINT `fk_source_taking1`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`taking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`money` (
  `id` INT NOT NULL,
  `amount` INT NULL,
  `currency` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `updated` VARCHAR(45) NULL,
  `created` VARCHAR(45) NULL,
  `taking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_money_taking1_idx` (`taking_id` ASC) VISIBLE,
  CONSTRAINT `fk_money_taking1`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`taking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`deposit_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`deposit_unit` (
  `id` INT NOT NULL,
  `deposit_id` INT NOT NULL,
  `taking_id` INT NOT NULL,
  `money_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deposit_unit_deposit_idx` (`deposit_id` ASC) VISIBLE,
  INDEX `fk_deposit_unit_taking1_idx` (`taking_id` ASC) VISIBLE,
  INDEX `fk_deposit_unit_money1_idx` (`money_id` ASC) VISIBLE,
  CONSTRAINT `fk_deposit_unit_deposit`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `stream`.`deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deposit_unit_taking1`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`taking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deposit_unit_money1`
    FOREIGN KEY (`money_id`)
    REFERENCES `stream`.`money` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `tag` VARCHAR(45) NULL,
  `updated` VARCHAR(45) NULL,
  `created` VARCHAR(45) NULL,
  `deposit_id` INT NOT NULL,
  `taking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_deposit1_idx` (`deposit_id` ASC) VISIBLE,
  INDEX `fk_user_taking1_idx` (`taking_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_deposit1`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `stream`.`deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_taking1`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`taking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`Crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`Crew` (
  `id` INT NOT NULL,
  `uuid` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `updated` VARCHAR(45) NULL,
  `created` VARCHAR(45) NULL,
  `taking_id` INT NOT NULL,
  `deposit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Crew_taking1_idx` (`taking_id` ASC) VISIBLE,
  INDEX `fk_Crew_deposit1_idx` (`deposit_id` ASC) VISIBLE,
  CONSTRAINT `fk_Crew_taking1`
    FOREIGN KEY (`taking_id`)
    REFERENCES `stream`.`taking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crew_deposit1`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `stream`.`deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stream`.`external`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stream`.`external` (
  `id` INT NOT NULL,
  `location` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `source_id` INT NOT NULL,
  `deposit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_external_source1_idx` (`source_id` ASC) VISIBLE,
  INDEX `fk_external_deposit1_idx` (`deposit_id` ASC) VISIBLE,
  CONSTRAINT `fk_external_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `stream`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_external_deposit1`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `stream`.`deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
