version: '3'

services:
  
#  drops-backend:
#    image: vivaconagua/drops-backend:latest
#    build: .
#    container_name: drops-backend
#    restart: unless-stopped
#    networks:
#      default:
#        ipv4_address: 172.2.100.1

#  stream-database:
#     image: mariadb
#     container_name: stream-database
#     environment: 
#      - MYSQL_DATABASE=stream 
#      - MYSQL_USER=stream
#      - MYSQL_PASSWORD=stream 
#      - MYSQL_ROOT_PASSWORD=yes 
#     restart: unless-stopped
#     volumes: 
#       - ./volumes/stream-database/mysql/:/var/lib/mysql/
#     networks:
#       default:
#         ipv4_address: 172.2.200.2

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.150.2

networks:
  default:
    external:
      name: pool-network
