FROM golang


RUN go get github.com/labstack/echo-contrib/session/...
RUN go get github.com/go-playground/validator/...
RUN go get github.com/rbcervilla/redisstore/...
RUN go get github.com/labstack/echo/...
RUN go get github.com/gocraft/dbr/...
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/jinzhu/configor/... 
RUN go get github.com/google/uuid/...

WORKDIR /app

ADD . /app

CMD ["go", "run", "server.go"]
