-- MySQL Script generated by MySQL Workbench
-- Sa 18 Jan 2020 13:05:47 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drops` ;
USE `drops` ;

-- -----------------------------------------------------
-- Table `drops`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NULL,
  `updated` BIGINT(8) NULL,
  `created` BIGINT(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`LoginInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`LoginInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_LoginInfo_User_idx` (`User_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_LoginInfo_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `drops`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`Profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Profile_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Profile_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `drops`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `pillar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`User_has_Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`User_has_Role` (
  `User_id` INT NOT NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `Role_id`),
  INDEX `fk_User_has_Role_Role1_idx` (`Role_id` ASC),
  CONSTRAINT `fk_User_has_Role_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `drops`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Role_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `drops`.`Role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
